name: interrupting

networks:
  default:
    name: interrupting

services:
  go-server:
    build: go
    container_name: go-server
    ports:
      - 8080:8080

  py-server:
    build: py
    container_name: py-server
    ports:
      - 5000:5000
